create table public.staffs (
  id uuid not null default gen_random_uuid (),
  employee_id text null,
  full_name_en text null,
  full_name_bn text null,
  profile_photo text null,
  signature text null,
  gender text null,
  date_of_birth date null,
  marital_status text null,
  religion text null,
  nationality text null default 'Bangladeshi'::text,
  blood_group text null,
  designation text null,
  type text null,
  subject text null,
  employment_type text null,
  joining_date date null,
  contact_number text null,
  alt_contact_number text null,
  email text null,
  emergency_contact text null,
  nid_number text null,
  birth_certificate text null,
  passport_number text null,
  created_at timestamp without time zone null default now(),
  constraint staffs_pkey primary key (id),
  constraint staffs_employee_id_key unique (employee_id)
) TABLESPACE pg_default;